name: Build documentation and push to github pages
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install mkdocs
        python -m pip install mkdocs-material
      
    - name: Config github commit details new commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Build & deploy site
      run: |
        python -m mkdocs gh-deploy
