name: Run tests and linting checks
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      reason:
        description: "Why are you running the pipeline manually?"
        required: true

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6

      - name: Checkout master
        uses: actions/checkout@v2

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        uses: suo/flake8-github-action@v1
        with:
          checkName: 'build'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
