name: Run tests and linting checks
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6

      - name: Checkout master
        uses: actions/checkout@v2

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: "spark"
          use-flake8: true
          extra-flake8-options: "--config=.flake8""
